platform :ios, '9.0'

target 'MyRecharge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyRecharge

  target 'MyRechargeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyRechargeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
