platform :ios, '9.0'
use_frameworks!

target 'MyRecharge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  pod 'SDWebImage', '~>3.8'
  pod 'Google/SignIn'
  # Pods for MyRecharge

  target 'MyRechargeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyRechargeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
